"""add image_url to properties

Revision ID: 06195f15651b
Revises: 2e5387c04a1f
Create Date: 2026-05-21 15:34:44.389549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06195f15651b'
down_revision: Union[str, Sequence[str], None] = '2e5387c04a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_properties_title'), table_name='properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_title'), 'properties', ['title'], unique=False)
    op.drop_column('properties', 'image_url')
    # ### end Alembic commands ###
