"""update property fields

Revision ID: 212d2754a6be
Revises: 8c936852fc7f
Create Date: 2026-05-21 16:27:01.523045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212d2754a6be'
down_revision: Union[str, Sequence[str], None] = '8c936852fc7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('description', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('city', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('properties', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('properties', 'created_at')
    op.drop_column('properties', 'rooms')
    op.drop_column('properties', 'city')
    op.drop_column('properties', 'price')
    op.drop_column('properties', 'description')
    # ### end Alembic commands ###
