"""add property contacts

Revision ID: 9401b1cf15b2
Revises: 136f31bdc8aa
Create Date: 2026-06-19 22:48:32.411460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9401b1cf15b2'
down_revision: Union[str, Sequence[str], None] = '136f31bdc8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('whatsapp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'whatsapp')
    op.drop_column('properties', 'phone')
    op.drop_column('properties', 'contact_name')
    # ### end Alembic commands ###
